### ISSUE TITLE
"Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable"

### ISSUE THREAD

**Issue by dracos** [actions/deploy-pages#1]
https://github.com/mysociety/fixmystreet/actions/runs/1589158554 as an example - build started appearing in Actions this evening, but doesn't appear to work, giving this error and also "failed to emit pages build telemetry".
No idea if related, but our Pages settings won't let us "Enforce HTTPS" without saying why, and I was pretty sure that was already activated (might be misremembering!).
The Pages themselves appear to be fine and up to date.
Hope that's helpful.

**Comment by tcbyrd** [comment]
@dracos Thanks for the report! We're addressing this now. We've rolled back the change that uses this action and are applying a fix before rolling it back out to users.
