### ISSUE TITLE
Failed to create deployment (status: 400)

### ISSUE THREAD

**Issue by cengique** [actions/deploy-pages#108]
Following the same code as in the [starter example for Github Pages](https://github.com/actions/starter-workflows/blob/main/pages/jekyll-gh-pages.yml) `deploy-pages` step results in the following error:
```
Error: Failed to create deployment (status: 400) with build version efba898182be4068f5a83d356f1a5bf241229025. Responded with: Invalid deployment branch and no branch protection rules set in the environment. Deployments are only allowed from gh-pages
```

As there is no way to specify the branch or protection rules, I do not know how to proceed. If this is not caused by code in deploy-pages, any insight would be appreciated. This is happening in [this repo](https://github.com/GGC-STaRS/GGC-STaRS.github.io/blob/master/.github/workflows/jekyll.yml).

**Comment by yoannchaudet** [comment]
In the settings for Pages on your repo, change the source from Branch to GitHub Actions. This will allow you to control Pages deployments with your workflow exclusively.

**Comment by cengique** [comment]
Ok, I didn't see that it was an option. However, I was trying use the official actions like this one in my own workflow. I think the reason for the error was because it was trying to do it from master and not gh-pages. So instead I would have to push to the gh-pages branch and then let Pages deploy that automatically?

**Comment by yoannchaudet** [comment]
It's either your site deploys from a branch and we enforce some security rules on your behalf. Or you use take control with GitHub Actions. The "official Actions" you refer to are designed for the later case.

**Comment by cengique** [comment]
I was trying to follow your advice, but the Github documentation for that feature is telling me to actually use your action from the default branch (see step 5): https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site

**Comment by cengique** [comment]
I create a clean version of the [workflow](https://github.com/GGC-STaRS/GGC-STaRS.github.io/blob/github-actions/.github/workflows/github-official.yml) and here's the [fail log](https://github.com/GGC-STaRS/GGC-STaRS.github.io/actions/runs/4148914923).
![image](https://user-images.githubusercontent.com/1424675/218228826-0f969fc4-a0a7-4ae4-9653-9e74f31f0b8f.png)

**Comment by yoannchaudet** [comment]
@cengique The documentation you are referring makes the assumption your Pages site is configured with Source = GitHub Actions in the settings.

> **When you configure your site to publish with GitHub Actions**, GitHub will suggest starter workflows for common publishing scenarios. The general flow of a workflow is to:

This is not the case for `GGC-STaRS/GGC-STaRS.github.io`. Follow the [steps here](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow) and try again.

**Comment by cengique** [comment]
@yoannchaudet the above screenshot was produced when I had Source="Github Actions" and when it didn't work, had reverted back. I just checked again in commit [13d4922](https://github.com/GGC-STaRS/GGC-STaRS.github.io/commit/13d4922b7d1873efd2a87b33e1df01882fda5083) with Source=GA and [this workflow](https://github.com/GGC-STaRS/GGC-STaRS.github.io/blob/github-actions/.github/workflows/github-official.yml), and I'm still getting the exact same error as in the above screenshot. Notice that this time it does not explicitly complain about not being on the `gh-pages` branch, but it's some other kind of environment protection. I do have the environment defined in the `deploy` step as follows:
```yaml
deploy:      
    # Deploy to the github-pages environment
    # (only accepts being run from gh-pages,
    # potentially in a separate workflow file)
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v1
```

**Comment by yoannchaudet** [comment]
@cengique Pages defines sensible security defaults for you. When you switch back and forth between Actions/branch publication, you have a bit of work to do.

You have full control over the branch protection for your environments in the settings of your repo (see [here](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-branches)).

This is an Actions check, not a Pages one:

![image](https://user-images.githubusercontent.com/14911070/218596161-01cfcdd2-d4f7-4757-8d67-7aa7c894151a.png)

**Comment by cengique** [comment]
That actually succeeded! I wasn't aware of the "Environments" section on the Settings page. So I will make sure that it's set up next time. Thanks again for helping with this.
