### ISSUE TITLE
Stuck at: Current status: updating_pages

### ISSUE THREAD

**Issue by kenorb** [actions/deploy-pages#11]
I've a static NextJS site in docs/ in gh-pages branch which deploys fine (although some assets aren't loaded properly).

When I've added `.nojekyll` file, the deployment to GitHub Pages fails.

```
Run actions/deploy-pages@v1-beta
  with:
    token: ***
    timeout: 600000
    error_count: 10
    reporting_interval: 1000
...
Created deployment for cfc1e8b406fd8512c59e94810188e48fbcd42229
...
Current status: deployment_queued
Current status: updating_pages
Current status: updating_pages
Current status: updating_pages
Error: Error: Request failed with status code 500
Sending telemetry for run id 1751510859
```

**Comment by tcbyrd** [comment]
@kenorb We had some issues this morning on the backend that prevented some deploys from going through. If you retry now it should work. Feel free to re-open this issue if you still have problems.
