### ISSUE TITLE
Add an additional input variable, with the URL of the destination repo

### ISSUE THREAD

**Issue by ilg-ul** [actions/deploy-pages#138]
I'm using a dual deploy mode for my GitHub Pages sites; pushes to the `master` branch are published in the `<organization>.github.io` repo, as usual, but pushes to the `develop` branch are published into an alternate `web-preview` repo, in an attempt to spot possible errors before the final publish.

With this `deploy-pages` action, if I got it right, it is only possible to publish into the same repo.

Would it be possible to add an additional input variable, with the URL of the destination repo, to allow publishing to alternate sites?

Thank you!

**Comment by JamesMGreene** [comment]
@ilg-ul Unfortunately, I feel that working across multiple repos isn't a practical extension to this Action (for that matter, _most_ Actions are intended to only work within a single repo).

It sounds like the feature you're describing is effectively trying to achieve preview deployments. The good news is that is a feature on our radar (available for GitHub internal alpha right now) 🎉 , but the bad news is that I cannot commit to an expected release date at this time as our team has some higher priorities to attend to right now. ⏳ 

In the meanwhile, as a short term workaround, you could use a Personal Access Token to push your `develop` branch related changes to the separate `web-preview`, and then have a separate Actions workflow in that repo to do the deployment.
