### ISSUE TITLE
 Error: No uploaded artifact was found!

### ISSUE THREAD

**Issue by mbrav** [actions/deploy-pages#14]
Getting an error with GithubPages. Stopped working in the span of 20 minutes between commits. No changes to configurations have been made.

```
Run actions/deploy-pages@v1-beta
  with:
    token: ***
    timeout: 600000
    error_count: 10
    reporting_interval: 1000
Actor: github-pages[bot]
Action ID: 1762005351
Artifact URL: https://pipelines.actions.githubusercontent.com/xRwahbJbEpFBFiI3me9E8FefKh0Q1vZDn1Byt2m1MCqCUxk23r/_apis/pipelines/workflows/1762005351/artifacts?api-version=6.0-preview
{"count":0,"value":[]}
Failed to create deployment for 7fac660be76d04c18f154ef418dad9a22c27c5dd.
Error: Error: No uploaded artifact was found! Please check if there are any errors at build step.
Error: Error: No uploaded artifact was found! Please check if there are any errors at build step.
```

**Comment by YiMysty** [comment]
👋 This message at most time means the build step failed. Please check if there are any issue at build step. Also include the link to the repo would be helpful to identify the issue like this.

**Comment by mbrav** [comment]
Hi @YiMysty , yes indeed, you are right. It was a build issue. Thank you for your answer, hope others will stumble upon it and read this issue.
