### ISSUE TITLE
Issue deploying github-pages artifact 

### ISSUE THREAD

**Issue by hamishteagle** [actions/deploy-pages#146]
Hi, 
I'm trying to use this (super useful) action within an Enterprise repo. When deploying the artifact I hit `502 Bad Gateway`.

```
Run actions/deploy-pages@v1
/usr/bin/docker exec  2c26655a51be600bc56174908587ac5480bdfbff0f0034b64f61f3cc66ce4c3d sh -c "cat /etc/*release | grep ^ID"
Artifact exchange URL: https://github.dev.global.***.org/_services/pipelines/4SaFpD3EjUqhAAtVcvhsnQhES2FTYURxZWSrLQNobqCTBubRoJ/_apis/pipelines/workflows/95573/artifacts?api-version=6.0-preview
Creating Pages deployment with payload:
{
	"artifact_url": "https://github.dev.global.***.org/_services/pipelines/4SaFpD3EjUqhAAtVcvhsnQhES2FTYURxZWSrLQNobqCTBubRoJ/_apis/pipelines/1/runs/848/artifacts?artifactName=github-pages&%24expand=SignedContent",
	"pages_build_version": "bc6b8[15](https://github.dev.global.***.org/BUS-DataScience/AIM-fresh-modelling/runs/735859?check_suite_focus=true#step:3:16)5dceab7608cd2f867a8b4fb96b96879de",
	"oidc_token": "***"
}
Error: Creating Pages deployment failed
Error: HttpError: <html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>

    at /__w/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at createPagesDeployment (/__w/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/src/api-client.js:1[16](https://github.dev.global.***/runs/735859?check_suite_focus=true#step:3:17):1)
    at Deployment.create (/__w/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/src/deployment.js:58:1)
    at main (/__w/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/src/index.js:30:1)
Error: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
```

Could anyone me help track down the issue? I'm struggling to figure out what the issue actually is from the error.

Thanks.

**Comment by yoannchaudet** [comment]
👋 Hello!

Do you know what version of GHES you are using? If not mistaken we only support Pages deployments with Actions in GHES 3.7+.

**Comment by hamishteagle** [comment]
Hi! 

We are using 3.7.7, so I guess it should be supported :)

**Comment by yoannchaudet** [comment]
I am wondering if you are still using https://github.com/actions/deploy-pages/releases/v1.2.7 indirectly. In GHES typically you have a copy of the whole `actions` organization in your appliance. And that one may be lagging behind. We accidentally broke the Actions for GHES customers and push a fix in version v1.2.8.

**Comment by JamesMGreene** [comment]
@yoannchaudet I don't think that's it. Even with `v1.2.7`, the HTTP response should be `404 Not Found` rather than a `502 Bad Gateway`.

@hamishteagle With a `502` response from the GitHub API, that's most commonly either a network timeout when an operation takes too long to complete, or, more rarely, a random transient error. 😓 

Please let us know if you're still running into this! I'm not sure if we can do much to assist on this one, though contacting GitHub Support might prove more helpful. 🤔

**Comment by JamesMGreene** [comment]
I'm going to close this out for now, but please feel free to reopen it or submit a new issue if you are still experiencing problems.

**Comment by raressabaubtrl** [comment]
hello. I'm experiencing the same problem on GHES 3.15.2 using actions/deploy-pages@v3.

Error message:


Error: Creating Pages deployment failed
Error: HttpError: <html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>

    at /home/runner/_work/_actions/actions/deploy-pages/v3/node_modules/@octokit/request/dist-node/index.js:124:1
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at createPagesDeployment (/home/runner/_work/_actions/actions/deploy-pages/v3/src/internal/api-client.js:126:1)
    at Deployment.create (/home/runner/_work/_actions/actions/deploy-pages/v3/src/internal/deployment.js:80:1)
    at main (/home/runner/_work/_actions/actions/deploy-pages/v3/src/index.js:30:1)
Error: Error: Failed to create deployment (status: 502) with build version aaefcc4fd91295759831732f901a[22](https://myenterpriseurl/nyorg/myrepo/actions/runs/676/job/34557#step:7:23)d47fa230b0. Server error, is githubstatus.com reporting a Pages outage? Please re-run the deployment at a later time.
