### ISSUE TITLE
 Deployment failed to report final status (GHES)

### ISSUE THREAD

**Issue by daibrahi** [actions/deploy-pages#152]
Hello Everyone,
I have seen similar issue which has been closed, however the issue still persists. We are using GHES and lately we started facing issues when we try to deploy to github pages.
I have read the related issue and tried changing the versions to 1,1.2.6,1.2.8 but the following error was displayed

![image](https://user-images.githubusercontent.com/48337074/229550998-0f439783-3a4a-40bc-a32d-eca0018b537d.png)

**Comment by yoannchaudet** [comment]
Can you confirm GitHub Pages is enabled for the repository?

**Comment by daibrahi** [comment]
@yoannchaudet thanks for your reply.
yes github pages is enabled for the repository and i have noticed the action fails in the following method

    async function getPagesDeploymentStatus({ githubToken, deploymentId }) {
      const octokit = github.getOctokit(githubToken)
      core.info('Getting Pages deployment status...')
      try {
        const response = await octokit.request('GET /repos/{owner}/{repo}/pages/deployment/status/{deploymentId}', {
          owner: github.context.repo.owner,
          repo: github.context.repo.repo,
          deploymentId
        })
    
        return response.data
      } catch (error) {
        core.error('Getting Pages deployment status failed', error)
        throw error
      }
    }
  
I assume the rest endpoint being called here is incorrect. See the docs for GHES v3.8 [GitHub Pages deployment ](https://docs.github.com/en/enterprise-server@3.8/rest/pages#create-a-github-pages-deployment)

**Comment by SirensOfTitan** [comment]
Also seeing this for GHES 3.8

**Comment by GuBee33** [comment]
I have the same issue with GitHub Enterprise Server 3.7.8
how could this be solved? Any suggestion?

**Comment by jtietema** [comment]
I wonder if this is related to #168 as we have this error with the v1 and the error mentioned in #168 with v2.
Github pages is enabled. We used v1 up until this point, but it started failing around the 23rd of March for us.

**Comment by daibrahi** [comment]
The issue concerns the GitHub enterprise appliance and nothing with this deploy-pages action, they are working on the fix and will soon patch with the release. 
keep an eye on https://enterprise.github.com/releases/ for the next release

**Comment by daibrahi** [comment]
The fix is released https://docs.github.com/en/enterprise-server@3.8/admin/release-notes

**Comment by JamesMGreene** [comment]
That's correct, GHES release [`3.8.3`](https://docs.github.com/en/enterprise-server@3.8/admin/release-notes#3.8.3-bugs) contains a bug fix for the `deployment_lost` scenario (which was an issue from beyond this action's boundaries).
