### ISSUE TITLE
jobs:   # Build job   build:     # <Not provided for brevity>     # At a minimum this job should upload artifacts using actions/upload-pages-artifact    # Deploy job   deploy:     # Add a dependency to the build job     needs: build      # Grant GITHUB_TOKEN the permissions required to make a Pages deployment     permissions:       pages: write      # to deploy to Pages       id-token: write   # to verify the deployment originates from an appropriate source      # Deploy to the github-pages environment     environment:       name: github-pages       url: ${{ steps.deployment.outputs.page_url }}      # Specify runner + deployment step     runs-on: ubuntu-latest     steps:       - name: Deploy to GitHub Pages         id: deployment         uses: actions/deploy-pages@v1

### ISSUE THREAD

**Issue by asimHussain1122** [actions/deploy-pages#162]
> Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/c/code-to-cloud/github-actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

**Comment by asimHussain1122** [comment]
Plzz submit

**Comment by yoannchaudet** [comment]
You can get some help at https://github.com/orgs/community/discussions/categories/pages?discussions_q=category%3APages+.
