### ISSUE TITLE
Show warning if Pages artifact size is greater than 1 GB

### ISSUE THREAD

**Issue by JamesMGreene** [actions/deploy-pages#164]
Assuming it is possible to get the artifact size of an in-progress workflow run without downloading that artifact to a runner, it would be a nice improvement to check the size of the Pages artifact to-be-deployed and then issue a warning message (but not outright fail, at least within the current major version of this action) if the [Pages Terms of Service limit of 1 GB](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits) is exceeded.

Related:
- https://github.com/actions/upload-pages-artifact/issues/59

**Comment by JamesMGreene** [comment]
Looks like we could probably get the `size` of the artifact when inspecting the response we are already retrieving during the [`getSignedArtifactUrl` call](https://github.com/actions/deploy-pages/blob/c9a8d971f4d157991d1649fbbb2f70d19b279a6f/src/internal/api-client.js#L91)

e.g. the mocked response from the `@actions/artifact` client tests includes a `size` property:

https://github.com/actions/toolkit/blob/457303960f03375db6f033e214b9f90d79c3fe5c/packages/artifact/__tests__/download.test.ts#L255-L277

So I'm thinking our current line of

```js
  const artifactRawUrl = data?.value?.find(artifact => artifact.name === artifactName)?.url
```

Could become something like:

```js
  const artifact = data?.value?.find(artifact => artifact.name === artifactName)
  const artifactRawUrl = artifact?.url
  const ONE_GIGABYTE = 1073741824
  if (artifact?.size > ONE_GIGABYTE) {
    core.warn('Uploaded artifact exceeds the allowed size for Pages deployments')
  }
```

I don't love mixing that into the `api-client.js` vs. keeping it with the business logic of `deployment.js` but it's probably reasonable. Otherwise we will also need to refactor the shape of the return value from the `getSignedArtifactUrl` function (and its references) to be an object including both the signed URL and the size. 🤔

**Comment by GretaP** [comment]
I was more concerned with ensuring the endpoint attributes are named properly. PR is in for this under the assumption that the API response includes a size attribute under data.
