### ISSUE TITLE
Warn if `timeout` input parameter value exceeds 10 minutes

### ISSUE THREAD

**Issue by JamesMGreene** [actions/deploy-pages#165]
The `timeout` input parameter is default to 10 minutes:

https://github.com/actions/deploy-pages/blob/af48cf94a42f2c634308b1c9dc0151830b6f190a/action.yml#L12-L15

However, that value is actually more than _just_ a default, it is also effectively a maximum as it also has to contend with the Pages deployment service's backend-enforced timeout of 10 minutes.

We should:
- [ ] Input the `action.yml` description to explain that
- [ ] Warn if that input parameter's value exceeds 10 minutes with an explanatory error message
  - [ ] This should probably be upgraded to an outright failure of the action step in a future major version bump

**Comment by beingme8583-netizen** [comment]
[inbound4448845293705837185.csv](https://github.com/user-attachments/files/27587891/inbound4448845293705837185.csv)
