### ISSUE TITLE
V2 not working with GHES 3.7

### ISSUE THREAD

**Issue by FloThinksPi** [actions/deploy-pages#168]
Apearently V2 of this action is incompatible with GHES3.7

```
Error: Creating Pages deployment failed
Error: HttpError: Not Found
    at /__w/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at createPagesDeployment (/__w/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/internal/api-client.js:116:1)
    at Deployment.create (/__w/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/internal/deployment.js:58:1)
    at main (/__w/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/index.js:30:1)
Error: Error: Failed to create deployment (status: 404) with build version cb8ac69b6379743b17029f637df101077fc70698. Ensure GitHub Pages has been enabled: https://github.enterprise.server/org/repo/settings/pages
```

In the release note i did not find any hint on this and also no documentation starting with what GHES version the V2 version of this action can be used. Could someone briefly add starting with which GHES version the V2 of this action is supposed to work ?

**Comment by jtietema** [comment]
We are currently facing a the same error on GHES 3.8.2, the v1 stopped working as well. I wonder if this was a GHES change that broke it, as I can't find a combination of old versions that work either....

**Comment by jkmgbrt** [comment]
Perhaps v2 is not compatible since the deployment API endpoints seems to have been changed in v2 to endpoints not corresponding with the ones described in the [GHES 3.8 docs](https://docs.github.com/en/enterprise-server@3.8/rest/pages#create-a-github-pages-deployment)?

https://github.com/actions/deploy-pages/compare/v1...v2
https://github.com/actions/deploy-pages/commit/b254707f5c3c910c335f3bcfd13a08eb14d18dca

**Comment by FloThinksPi** [comment]
@jtietema Yea defenetely not supported for GHES 3.7 and 3.8. Since the action supports GHES in general i am just missing information (docs) here with Starting what GHES version V2 of this action is supported. I suppose things will also stop working on a GHES update when running V1 of this action and then every workflow needs to change to V2 ? Maybe there is some information to share on this too ?

**Comment by JamesMGreene** [comment]
You are correct that `v2` of this action will not work with any of the currently released GHES versions.

As far as we know, however, every version of this action under the `v1` series, including the latest `v1`, should work successfully for GHES with the specific **EXCEPTION** of:
- [`v1.2.7`](https://github.com/actions/deploy-pages/releases/tag/v1.2.7) will **NOT** work for GHES. Related: https://github.com/actions/deploy-pages/issues/137

Could you please attempt to use one of those `v1`/`v1.x.x` versions instead? Let us know if you're still running into issues. Thank you, and apologies for the confusion! 🙇🏻

**Comment by JamesMGreene** [comment]
I've added a compatibility table into the README and a note about it into future release notes:
- https://github.com/actions/deploy-pages/pull/173

If you're still struggling to get this action working with GHES when using the `v1` series, please feel free to reopen this issue or create a new one. Thanks for helping us expand our understanding of how GHES users are consuming our actions! 🙇🏻
