### ISSUE TITLE
Cannot deploy artifact due to error

### ISSUE THREAD

**Issue by Luxusio** [actions/deploy-pages#179]
Cannot deploy artifact with error message.

`Error: Artifact could not be deployed. Please ensure the content does not contain any hard links, symlinks and total size is less than 10GB.`

But it seems there's no hard links, symlinks. And artifact size is smaller than 1MB.
What is the problem?

[Repository](https://github.com/Luxusio/gh-pages-deploy-pages-action-sample)

I found #66, but it didn't help.

**Comment by Luxusio** [comment]
I changed upload artifact action from `actions/upload-artifact@v3` to `actions/upload-pages-artifact@v1`.
It solved my problem.

**Comment by FrankFan** [comment]
> I changed upload artifact action from `actions/upload-artifact@v3` to `actions/upload-pages-artifact@v1`. It solved my problem.

`actions/upload-pages-artifact@v1` is deprecated recently.

> depoly
Error: No artifacts named "dist" were found for this workflow run. Ensure artifacts are uploaded with actions/upload-artifact@v4 or later.


the workflow file is :

 - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: dist
          path: ./dist/
