### ISSUE TITLE
`preview` timeline?

### ISSUE THREAD

**Issue by janosh** [actions/deploy-pages#180]
Curious about the timeline for the [`preview` feature](https://github.com/actions/deploy-pages/tree/b580d214b4e13b2a70d0e04376a86ed862ebb558#inputs-) exciting alpha. The most important missing GH Pages feature for me coming from netlify/vercel.

**Comment by yoannchaudet** [comment]
We do not have a timeline to share at the moment unfortunately.

**Comment by sethicis** [comment]
Just want to echo my anticipation of this feature. + :100:

**Comment by lauthieb** [comment]
+1 please 🙏

**Comment by rickstaa** [comment]
@yoannchaudet, thanks for the update. Is there already a way to use this alpha before it is released? I tried to simply set the `preview` argument, but this will deploy to the main URL 🤔.

**Comment by lauthieb** [comment]
> @yoannchaudet, thanks for the update. Is there already a way to use this alpha before it is released? I tried to set the `preview` argument, but this will deploy to the main URL 🤔.

+1 🙏

**Comment by rickstaa** [comment]
> > @yoannchaudet, thanks for the update. Is there already a way to use this alpha before it is released? I tried to set the `preview` argument, but this will deploy to the main URL 🤔.
> 
> +1 🙏

Nevermind, I just found a comment by the Team that states it currently is only available to GitHub employees or GitHub Open-source projects (see https://github.com/actions/deploy-pages/pull/61#issue-1368417271). @yoannchaudet is this comment still up to date 🤔?

**Comment by vincerubinetti** [comment]
I'm sure the GitHub team is aware of this, but I have to imagine that having this feature could make them a LOT of money. In the same way gh-actions made me never use (or pay for) another CI service again, this would make me never use Netlify again, and my company would happily pay to have no-setup PR previews 😇

I'm sure the infrastructure to support this is immense, though. Probably would increase the number of pages sites by an order of magnitude, given that each pages repo would have multiple previews open at the same time on average. And then setting up the [subdomains](https://github.com/orgs/community/discussions/7730#discussioncomment-4219424) (if that's how they do it) can't be trivial.
