### ISSUE TITLE
 Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable from PR

### ISSUE THREAD

**Issue by linonetwo** [actions/deploy-pages#184]
https://github.com/tiddly-gittly/intention-tower-knowledge-graph/actions/runs/5230969329/jobs/9444826900?pr=21

I have permissions in .yaml

https://github.com/tiddly-gittly/intention-tower-knowledge-graph/blob/50ad2da68da3027403565bf6b880a6520f501c0e/.github/workflows/release.yml#L23-L27

My push is working properly, but PR-er fails

**Comment by JamesMGreene** [comment]
Two things of note here:
- First, similar to discussion in #45, GitHub Pages does not currently support deploying from PRs yet.
- Second, the [PR you referenced](https://github.com/tiddly-gittly/intention-tower-knowledge-graph/pull/21) was from a **forked repository**. The `pull_request` event for PRs from forks are not given access to any Actions Secrets (excluding `GITHUB_TOKEN`) for security reasons. You can read more about this in [this Security Lab writeup](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/), which also mentions some potential workarounds like using the `pull_request_target` event trigger.

**Comment by linonetwo** [comment]
Thanks, I understand, this is limitation from Github. They are not prepared for deploying test page with Github Pages. They might think this is the job of netlify or zeit.
