### ISSUE TITLE
Usage without actions/jekyll-build-pages

### ISSUE THREAD

**Issue by letmaik** [actions/deploy-pages#20]
I'm assuming the goal for actions/deploy-pages is to provide a generic way to deploy a zipped-up dump of a website following some conventions on artifact naming and the contents of the artifact.

Looking at the artifacts, it seems like the convention currently is:
- Artifact name: "github-pages"
- Artifact content: single tar file named `artifact.tar` that contains the website files

Two questions:
1. Why the extra tar file? Wouldn't it be simpler to just have the website files directly in the artifact so that actions/upload-artifact can be used directly on a folder?
2. Will these conventions change and should people wait before using actions/deploy-pages without actions/jekyll-build-pages?

**Comment by YiMysty** [comment]
👋 @letmaik 
To answer your questions
> 1. Why the extra tar file? Wouldn't it be simpler to just have the website files directly in the artifact so that actions/upload-artifact can be used directly on a folder?

There are some known issues for `upload-artifact` actions. Please check https://github.com/actions/upload-artifact#zipped-artifact-downloads for more details.

> 2. Will these conventions change and should people wait before using actions/deploy-pages without actions/jekyll-build-pages?

We are going to start with "BYOW" (bring your own workflow) feature soon. In the mean time, feel free to check https://github.com/actions/deploy-pages/issues/9 to integrate your own workflow.

**Comment by letmaik** [comment]
@YiMysty Thanks!

> There are some known issues for `upload-artifact` actions. Please check https://github.com/actions/upload-artifact#zipped-artifact-downloads for more details.

The link just describes the behavior that downloading gives you a zip file. What issues are you referring to?

**Comment by YiMysty** [comment]
👋 pages backend gonna download the uploaded artifact, and then do the deployment.
>  If file permissions and case sensitivity are required, you can tar all of your files together before artifact upload. Post download, the tar file will maintain file permissions and case sensitivity:

tar content is the recommended way to avoid this situation.

**Comment by letmaik** [comment]
I think file permissions don't matter, so this is just about case sensitivity. Shame that artifacts have this behavior, but ok. Maybe there will be some action that can tar things up. I'd hate to see variations of the tar command in each repo... especially since it will vary across operating systems.

**Comment by yoannchaudet** [comment]
When we officially support custom workflow for deploying Pages, we will very much likely update the `deploy-pages` action (this repo!) to accept a folder as an optional input and do all the `tar` + upload artifact magic underneath.

**Comment by letmaik** [comment]
@yoannchaudet Sounds great! I'll leave it to you to close this issue or leave it open. I got all my answers :)

**Comment by letmaik** [comment]
I tried this out now but couldn't get it to work yet.

https://github.com/letmaik/t_cose/runs/5545277167?check_suite_focus=true

> Failed to create deployment for 10b883b911e60234044520c8e7ac9b7789b63d37.
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-github-pages-deployment"}

https://github.com/letmaik/t_cose/blob/10b883b911e60234044520c8e7ac9b7789b63d37/.github/workflows/pages.yml#L12-L46

**Comment by YiMysty** [comment]
> I tried this out now but couldn't get it to work yet.
> 
> https://github.com/letmaik/t_cose/runs/5545277167?check_suite_focus=true
> 
> > Failed to create deployment for 10b883b911e60234044520c8e7ac9b7789b63d37.
> > {"message":"Not Found","documentation_url":"[https://docs.github.com/rest/reference/repos#create-a-github-pages-deployment"}](https://docs.github.com/rest/reference/repos#create-a-github-pages-deployment%22%7D)
> 
> https://github.com/letmaik/t_cose/blob/10b883b911e60234044520c8e7ac9b7789b63d37/.github/workflows/pages.yml#L12-L46

👋 you need to enable GitHub pages first before you can use this action. e.g. go to settings page and click enable pages.

**Comment by letmaik** [comment]
Hm, I only see the following to enable it, but then it builds/deploys automatically from the selected branch. Wouldn't this conflict with manually calling actions/deploy-pages? I guess the UI has to be changed first?

![image](https://user-images.githubusercontent.com/530988/158327229-44ad6ca5-df00-4dd5-bc92-bafd0f5aa20a.png)

**Comment by letmaik** [comment]
One more note/question: I think currently the deploy permission is kind of linked to a branch, but what I usually do is deploy project docs whenever I release a new version, and I usually trigger that by pushing a git tag which builds and tests the code, and then generates the docs and eventually pushes it to `gh-pages`. Will `actions/deploy-pages` also support running from git tags?

**Comment by YiMysty** [comment]
> Hm, I only see the following to enable it, but then it builds/deploys automatically from the selected branch. Wouldn't this conflict with manually calling actions/deploy-pages? I guess the UI has to be changed first?

👋 We will fix the UX (to tie with environment instead of branch) when we start to work on customize workflow feature. For now you could enable the pages for a non-related branch. (Just for enable pages.)

Go to the `Environments` section under settings tab, and edit `github-pages` environment. change the deployment branches to protected branches

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/8811182/158427519-3098a858-ca11-4854-b672-3af15dbf93e3.png">

Now you would be able to do the deployment for the branch you want the workflow to run :)

> One more note/question: I think currently the deploy permission is kind of linked to a branch, but what I usually do is deploy project docs whenever I release a new version, and I usually trigger that by pushing a git tag which builds and tests the code, and then generates the docs and eventually pushes it to gh-pages. Will actions/deploy-pages also support running from git tags?

for the customize in the future, we will design ux to allow trigger from workflow directly. At that case, you would be able to define your owner trigger for when to run `deploy-pages`

**Comment by SamStephens** [comment]
@YiMisty thanks for the explanations you've provided here. I've used this to create a parallel to actions/jekyll-build-pages, [SamStephens/nanoc-build-pages](https://github.com/SamStephens/nanoc-build-pages), for using nanoc to build Github pages.

**Comment by yoannchaudet** [comment]
Here is something new! 

https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/

The [README file](https://github.com/actions/deploy-pages#readme) on this repo contains further information too. Closing here but let us know if you have further questions.
