### ISSUE TITLE
Publish to Marketplace?

### ISSUE THREAD

**Issue by webknjaz** [actions/deploy-pages#212]
Is there a reason this action isn't listed on the marketplace? Many people can find unofficial actions related to publishing to GH Pages but not this one.

I noticed that `name:` in `action.yml` contains spaces and I'm not sure if that's allowed on the Marketplace side. Should this be fixed?

**Comment by Notexe** [comment]
It's on the marketplace already https://github.com/marketplace/actions/deploy-github-pages-site

**Comment by webknjaz** [comment]
Anyway, seems like this can be closed.
