### ISSUE TITLE
When depended-upon build phase fails, whole site becomes a 404.

### ISSUE THREAD

**Issue by dabrahams** [actions/deploy-pages#214]
> Issues should only be opened on if the issue **relates to code in this repository**.

I cannot know that with absolute certainty; apologies if it turns out to be a GitHub bug for example.

I [followed](https://github.com/hylo-lang/hylo/blob/eca5086/.github/workflows/doc-extraction.yml) the recipe in the README, but was surprised to find that when the `build` step fails (which happens non-deterministically for unknown reasons), the entire previously-deployed site disappears and becomes a 404 (the site is served from https://hylo-lang.org/hylo).  I'd have guessed that the `needs: build` line would prevent this plugin from having any effect unless build succeeds, but I can't think of any other explanation for this effect.  Is it intentional?  Is it unrelated to this plugin?

Thanks!

**Comment by JamesMGreene** [comment]
Are you referring to this workflow run failure?
https://github.com/hylo-lang/hylo/actions/runs/6293268844

If so, I would agree with you that that workflow run should not have resulted in any change to your published Pages site. 🤔 

Are you able to reproduce this same issue?

**Comment by JamesMGreene** [comment]
Please feel free to reopen the issue if you're still running into this. 🤷
