### ISSUE TITLE
Deployment to pages via `actions/deploy-pages@v2` fails - file permissions

### ISSUE THREAD

**Issue by NukeManDan** [actions/deploy-pages#222]
See https://github.com/orgs/community/discussions/66706#discussion-5613026 , I very much doubt it's the action, but figured I would ask here and see if it is perhaps a bug or a misconfig on my end.

**Comment by NukeManDan** [comment]
@JamesMGreene I hate to ping, but this is blocking my pages from deploying at all now that this action is needed to get it there :pray:

**Comment by NukeManDan** [comment]
https://github.com/actions/deploy-pages/issues/188#issuecomment-1629531844

Was the fix - sorry for the noise! :face_with_spiral_eyes:

**Comment by Shubham4u4** [comment]
I have an issue i am unable to visit my web page
as it shown after click on the link of GitHub 
![Screenshot_2023-09-24-04-09-15-43_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/actions/deploy-pages/assets/113795417/81025df0-4bd2-48d2-bc54-b4d705a1ff86)
