### ISSUE TITLE
Will my GitHub Pages website stop working if artifacts expire?

### ISSUE THREAD

**Issue by mrpandey** [actions/deploy-pages#249]
This action deploys generated artifacts to GitHub pages.
However, Action artifacts have a limited retention period.
I am curious about what happens when these artifacts expire.

Q1. Does the website stop working after artifacts expire?

Q2. If not, then it means that static files in artifacts were copied somewhere for GitHub pages to serve it. Where are these files? Can I view and access them?

**Comment by JamesMGreene** [comment]
> Q1. Does the website stop working after artifacts expire?

No. 🚀 

> Q2. If not, then it means that static files in artifacts were copied somewhere for GitHub pages to serve it.

Yes. 👍 

> Where are these files?

They are replicated across a set of multiple Pages distributed filesystem servers when they are deployed. From there, the files are served with NGINX.

> Can I view and access them?

No, not as a filesystem nor artifact bundle.

There was some discussion around something similar in another repo, if you're curious:
- https://github.com/actions/upload-pages-artifact/issues/57
