### ISSUE TITLE
Is there a way to use this in the composite action?

### ISSUE THREAD

**Issue by smorimoto** [actions/deploy-pages#273]
I don't think the environment field is available in the composite action, but is it strictly not required?

**Comment by JamesMGreene** [comment]
The Actions [`environment` field](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenvironment) is definitely required for this action to succeed.

It is part of the data that is factored into the OIDC token that gets generated for deployment validation.

**Comment by smorimoto** [comment]
Hmm? Oddly, even if it does not exist, the action succeeded and the deployment was done...

**Comment by JamesMGreene** [comment]
@smorimoto Any chance you can share your workflow file? 🤔
