### ISSUE TITLE
Actions fail after update actions/deploy-pages to v4 and actions/upload-pages-artifact to v3 

### ISSUE THREAD

**Issue by torn4dom4n** [actions/deploy-pages#284]
I just updated actions/deploy-pages to v4 and actions/upload-pages-artifact to v3 in [my repo](https://github.com/AREA44/astro-research-theme) and got this error:
```yml
Run actions/deploy-pages@v4
Fetching artifact metadata for github-pages in run 7264600[9](https://github.com/AREA44/astro-research-theme/actions/runs/7264600911/job/19792767463#step:2:10)[11](https://github.com/AREA44/astro-research-theme/actions/runs/7264600911/job/19792767463#step:2:12)
Creating Pages deployment with payload:
{
	"artifact_id": 1[12](https://github.com/AREA44/astro-research-theme/actions/runs/7264600911/job/19792767463#step:2:13)45035[14](https://github.com/AREA44/astro-research-theme/actions/runs/7264600911/job/19792767463#step:2:15),
	"pages_build_version": "cf67bf05e7d24c255c38726ac891fe4b93fbf25b",
	"oidc_token": "***"
}
Error: Creating Pages deployment failed
Error: HttpError: No artifact_url provided
    at /home/runner/work/_actions/actions/deploy-pages/v4/node_modules/@octokit/request/dist-node/index.js:124:1
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at createPagesDeployment (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/api-client.js:68:1)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/deployment.js:78:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v4/src/index.js:30:1)
Error: Error: Failed to create deployment (status: 400) with build version cf67bf05e7d24c255c38726ac891fe4b93fbf25b. Responded with: No artifact_url provided
```
Full log [here](https://github.com/AREA44/astro-research-theme/actions/runs/7264600911).

**Comment by petter** [comment]
Also experiencing this: https://github.com/domstolene/designsystem/actions/runs/7264875307/job/19793326264

**Comment by luizrcs** [comment]
Same here, and it's driving me crazy. I explicitly checked the failed job logs and it says right at the beginning the `pages` write permission is given.

**Comment by SaptarshiSarkar12** [comment]
Same here - https://github.com/SaptarshiSarkar12/Drifty/actions/runs/7270487603

**Comment by SaptarshiSarkar12** [comment]
@JamesMGreene Please look into this issue as soon as possible. #287 seems to be a good fix.

**Comment by davwheat** [comment]
It's currently 10pm in Minneapolis (where his GitHub profile says he's based). Be patient. Workarounds exist.

**Comment by SaptarshiSarkar12** [comment]
Oh, yeah. I forgot to check his timezone. I'm extremely sorry.
Thank you for informing @davwheat :grin:!

**Comment by orhun** [comment]
Same error here: https://github.com/orhun/git-cliff/actions/runs/7274801940/job/19821456493

**Comment by afh** [comment]
Ledger's project website https://ledger-cli.org is also affected by this (see https://github.com/ledger/ledger.github.io/actions/runs/7272871676/job/19828971150)

**Comment by davwheat** [comment]
> This is probably due to your workflows missing the newly required `actions: read` permission for `v4`.

It is not. See: https://github.com/davwheat/rail-announcements/actions/runs/7270687779

Workflow: https://github.com/davwheat/rail-announcements/blob/4e2b36306630d1fdfe825e658677979e392a65b7/.github/workflows/smoketest.yml#L89-L92

**Comment by mikesprague** [comment]
> But, as a short-term workaround, I believe adding the `actions: read` permission to your workflow/job will alleviate this blocker.

This also did not work for me. Same error as without it:

```shell
Fetching artifact metadata for pages-api-endpoints in run 7278395179
Creating Pages deployment with payload:
{
	"artifact_id": 1[12](https://github.com/mikesprague/api/actions/runs/7278395179/job/19832554835#step:5:13)705[13](https://github.com/mikesprague/api/actions/runs/7278395179/job/19832554835#step:5:14)38,
	"pages_build_version": "8aff0377aa9ad37ed46fce84654616e21a0f4cd0",
	"oidc_token": "***"
}
Error: Creating Pages deployment failed
Error: HttpError: No artifact_url provided
```

**Comment by JamesMGreene** [comment]
Yup, we've identified an issue on the API internal side. A fix is in progress and should be rolled out in the next few hours. Thank you all for your reporting and patience, and our apologies for the temporary inconvenience! 🙇 

P.S. If anyone needs a short-term workaround, please revert to using the previous major versions of `actions/upload-pages-artifact` and `actions/deploy-pages` until we can get the fix shipped.

**Comment by davwheat** [comment]
Thanks for tracking this down! :)

**Comment by JamesMGreene** [comment]
We believe this should be resolved as of ~4 hours ago, assuming you also include the `actions: read` permission (for now). Please give it another try, but do let us know if you still encounter friction. 🙇

**Comment by SaptarshiSarkar12** [comment]
@JamesMGreene Yes, it works now :+1: - https://github.com/SaptarshiSarkar12/Drifty/actions/runs/7283610116.
Awesome support :clap:, thank you @JamesMGreene :grin:.

**Comment by afh** [comment]
Confirming Github actions for the [ledger/ledger.github.io](https://github.com/ledger/ledger.github.io/actions/runs/7287587089) repo are back to ✅. Thanks for resolving this, much appreciated 👍

**Comment by JamesMGreene** [comment]
📣 The latest release, [`v4.0.1`](https://github.com/actions/deploy-pages/releases/tag/v4.0.1), has **removed** the need for the `actions: read` permission that `v4.0.0` introduced. 🪓

**Comment by hugolpz** [comment]
I went to and changed the option : 
```
Settings > Actions > General 
Actions permissions
(o) Allow all actions and reusable workflows
```

![image](https://github.com/user-attachments/assets/753b4142-6a4c-409d-9d91-6be49be108da)
