### ISSUE TITLE
Bump to V4 broke the deploy step

### ISSUE THREAD

**Issue by AndreiBarbuOz** [actions/deploy-pages#286]
Initial failure with permissions:
```
permissions:
  contents: read
  pages: write
  id-token: write
```
resulted in:
```
Fetching artifact metadata for github-pages in run 0000000000
Error: Fetching artifact metadata failed. Is githubstatus.com reporting issues with API requests, Pages or Actions? Please re-run the deployment at a later time.
Error: HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/actions/deploy-pages/v4/node_modules/@octokit/request/dist-node/index.js:124:1
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getArtifactMetadata (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/api-client.js:[10](https://github.com/0000000000/actions/runs/0000000000/job/0000000000#step:2:11):1)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/deployment.js:66:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v4/src/index.js:30:1)
Error: Error: Failed to create deployment (status: 403) with build version 0000000000[15](https://github.com/0000000000/actions/runs/0000000000/job/0000000000#step:2:16). Ensure GITHUB_TOKEN has permission "pages: write".
```

After updated the permissions to:
```
permissions:
  contents: read
  pages: write
  id-token: write
  actions: read
```

New failure:
```
Fetching artifact metadata for github-pages in run 0000000000
Creating Pages deployment with payload:
{
	"artifact_id": [11](https://github.com/0000000000/actions/runs/0000000000/job/0000000000#step:2:12)0000000000,
	"pages_build_version": "0000000000",
	"oidc_token": 0000000000"
}
Error: Creating Pages deployment failed
Error: HttpError: No artifact_url provided
    at /home/runner/work/_actions/actions/deploy-pages/v4/node_modules/@octokit/request/dist-node/index.js:[12](https://github.com/0000000000/actions/runs/0000000000/job/0000000000#step:2:13)4:1
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at createPagesDeployment (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/api-client.js:68:1)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/deployment.js:78:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v4/src/index.js:30:1)
Error: Error: Failed to create deployment (status: 400) with build version 0000000000[16](https://github.com/0000000000/actions/runs/0000000000/job/0000000000#step:2:17)0000000000[19](https://github.com/0000000000/actions/runs/0000000000/job/0000000000#step:2:20)0000000000. Responded with: No artifact_url provided
```

**Comment by luizrcs** [comment]
Same here, and it's driving me crazy. I explicitly checked the failed job logs and it says right at the beginning the `pages` write permission is given.

**Comment by Ry0taK** [comment]
It looks like the following commit changed the `artifact_url` parameter to the `artifact_id`: https://github.com/actions/deploy-pages/commit/b12897a760d97ad2a3315379d85b4b730c3d4b43
Since [Create a GitHub Pages deployment](https://docs.github.com/en/rest/pages/pages?apiVersion=2022-11-28#create-a-github-pages-deployment) endpoint requires artifact_url, I believe this change needs to be reverted

**Comment by jamezp** [comment]
Just another same here https://github.com/wildfly/wildfly-maven-plugin/actions/runs/7270026747

**Comment by JamesMGreene** [comment]
You correctly identified the first issue that workflows will need the newly required `actions: read` permission for `v4` (`v4.0.0`, at least).

https://github.com/actions/deploy-pages/pull/283/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R33

We're going to investigate removing the need for that new permission in an in-flight follow-up PR today, so please bear with us:
- #288 

But, as a short-term workaround, I believe adding the `actions: read` permission to your workflow/job will be required for now.

The second issue you're hitting is a bit more of a mystery offhand. We'll investigate today! 🔍

**Comment by JamesMGreene** [comment]
We've identified an issue on the API internal side. A fix is in progress and should be rolled out in the next few hours. Thank you all for your reporting and patience, and our apologies for the temporary inconvenience! 🙇 

P.S. If anyone needs a short-term workaround, please revert to using the previous major versions of `actions/upload-pages-artifact` and `actions/deploy-pages` until we can get the fix shipped.

**Comment by JamesMGreene** [comment]
We believe this should be resolved as of ~4 hours ago, assuming you also include the `actions: read` permission (for now). Please give it another try, but do let us know if you still encounter friction. 🙇

**Comment by ollegkz** [comment]
Still failing on v4 here https://github.com/ollegkz/olle.coffee/actions/runs/7285230140 (with read permissions for actions) :(

**Comment by JamesMGreene** [comment]
@ollegkz You need to update your build job to use `actions/upload-pages-artifact@v3` as well. They're using a new service, so both the upload and deploy have to be targeting it.

**Comment by ollegkz** [comment]
Aww, long wait then I guess D: https://github.com/withastro/action/blob/main/action.yml#L96. Thanks for the explanation <3

**Comment by JamesMGreene** [comment]
📣 The latest release, [`v4.0.1`](https://github.com/actions/deploy-pages/releases/tag/v4.0.1), has **removed** the need for the `actions: read` permission that `v4.0.0` introduced. 🪓
