### ISSUE TITLE
Unhelpful Error

### ISSUE THREAD

**Issue by SiliconSelf** [actions/deploy-pages#292]
When trying to deploy my site built with Hugo, I get the error "Deployment failed, try again later." as the only error-related output in my entire pipeline, even with debug output enabled. I found #51 which says a bunch of changes have been made around error handling, but I'm still getting the same error on version 4.0.2. What does this error actually mean?

My failing action:
https://github.com/SiliconSelf/siliconself.github.io/actions/runs/7340798903/job/19987430009

**Comment by ArcaneNibble** [comment]
"Me too"

 It was working on the 22nd of December, has been failing just now, including deploying the exact same code that was deployed successfully on the 22nd

**Comment by ArcaneNibble** [comment]
Explicitly reverting to v4.0.1 or v4.0.0 (instead of simply v4) also does not help

**Comment by JamesMGreene** [comment]
Thank you for the reporting, and apologies for the unhelpful error message! 🙇 

We are aware of it and investigating. You can check on the current incident status at https://www.githubstatus.com/incidents/hzd6d6xhjpl6

If you need to deploy urgently, the only workaround at the moment would be to revert to using `actions/upload-pages-artifact@v2` and `actions/deploy-pages@v3`.

**Comment by SiliconSelf** [comment]
Hi James, I was actually just in the middle of typing a comment including that link. As for making the error more useful, maybe the raw error could also be included in `core.error` in addition to the error messages so we can get more insight into why our actions fail?

**Comment by JamesMGreene** [comment]
Unfortunately, given the types of errors that cause this blanket "deployment failed" scenario, we tend to not want to expose them since they're related to some more sensitive internal bits. 😓 

Anyway, good news: the problem was identified, corrected, deployed, and Pages should be back to fully operational status now. 🚀
