### ISSUE TITLE
Page Deployment Failing Periodically with Timeouts since Upgrade to v4

### ISSUE THREAD

**Issue by barndawgie** [actions/deploy-pages#293]
We recently upgraded to deploy-pages@v4 and have seen periodic workflow failures since. So far, these failures always succeed on manual retry.

Here is an example of a failed workflow:
https://github.com/esphome-econet/esphome-econet/actions/runs/7340611546/attempts/1

It succeeded on retry here:
https://github.com/esphome-econet/esphome-econet/actions/runs/7340611546/attempts/2

**Comment by JamesMGreene** [comment]
Thanks for reporting! You should hopefully see less of this as of the new `v4.0.3` (and updated `v4`). 🤞 

Related:
- https://github.com/actions/toolkit/pull/1613

If the issue persists after upgrading, please reach out to us again! ❤ 🙇
