### ISSUE TITLE
Getting "Fetching artifact metadata failed."

### ISSUE THREAD

**Issue by phryneas** [actions/deploy-pages#294]
Hi,
I'm still experiencing the "Fetching artifact metadata failed." error.

This apparently was a problem in 4.0.0 that *should* be fixed in 4.0.1, but I'm still experiencing it in 4.0.2 - even with an added `actions: read` permission.

You can see a failed deployment here: https://github.com/phryneas/ssr-only-secrets/actions/runs/7420900436/job/20193170290

And this is the related workflow: https://github.com/phryneas/ssr-only-secrets/blob/main/.github/workflows/docs.yml

**Comment by febus982** [comment]
> Hi, I'm still experiencing the "Fetching artifact metadata failed." error.
> 
> This apparently was a problem in 4.0.0 that _should_ be fixed in 4.0.1, but I'm still experiencing it in 4.0.2 - even with an added `actions: read` permission.
> 
> You can see a failed deployment here: https://github.com/phryneas/ssr-only-secrets/actions/runs/7420900436/job/20193170290
> 
> And this is the related workflow: https://github.com/phryneas/ssr-only-secrets/blob/main/.github/workflows/docs.yml

Apparently you have to bump up the `actions/upload-pages-artifact` version to `v3` here: https://github.com/phryneas/ssr-only-secrets/blob/616a9b0831829f7770494107cc0518cad7fd490c/.github/workflows/docs.yml#L38

It would be great if this were mentioned somewhere in the documentation, though.

**Comment by phryneas** [comment]
Tbh., I didn't even know there was a v3 - the [README](https://github.com/actions/upload-pages-artifact) of that action still shows v2 😅 

I'll give it a try :)

**Comment by phryneas** [comment]
That worked out, thank you so much! :)
