### ISSUE TITLE
CNAME file doesn't work to set custom domain

### ISSUE THREAD

**Issue by scriptype** [actions/deploy-pages#304]
Hi, I'm actually not sure if this is the right place for this issue, but here it is.

I've recently switched the pages setting of my repository to use github actions:

<img width="353" alt="image" src="https://github.com/actions/deploy-pages/assets/5516876/6a7b08b3-72de-46bb-8a67-ad83a60411c6">

When I was using the "deploy from a branch" option, GitHub was automatically seeing the cname file in the `docs` folder (pages folder) to set up custom domain. This was useful because the file was being automatically generated based on static site generator configuration.

I have noticed this cname file is no longer useful since I switched to using `actions/deploy-pages`. It would be sweet if cname file just worked like before, or alternatively, if the action had an input for cname.

Just to be clear, the problem is having to enter the custom domain by hand in the github pages settings UI when using `actions/deploy-pages`.

**Comment by EvanCarroll** [comment]
[The documentation certainly seems to indicate that it should work](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site)

> Under "Custom domain", type your custom domain, then click Save. If you are publishing your site from a branch, this will create a commit that adds a CNAME file directly to the root of your source branch. **If you are publishing your site with a custom GitHub Actions workflow, no CNAME file is created, so you need to create one manually (containing only a line of text with your custom domain). For more information about your publishing source, see "Configuring a publishing source for your GitHub Pages site."**

**Comment by EvanCarroll** [comment]
I had the same problem having uploaded a CNAME file, here was my solution https://devops.stackexchange.com/a/19892/18965

**Comment by yoannchaudet** [comment]
This is by design.

The `CNAME` file is only an option for setting up custom domain when deploying from a branch. To set a custom domain in a custom workflow, one could make some API calls. It is not something we recommend.

**Comment by EvanCarroll** [comment]
@yoannchaudet  not what the docs say,

>  If you are publishing your site with a custom GitHub Actions workflow, no CNAME file is created,** so you need to create one manually (containing only a line of text with your custom domain).**

**Comment by yoannchaudet** [comment]
Do you have a link handy so I can get it updated?
