### ISSUE TITLE
Value 'github-pages' is not valid

### ISSUE THREAD

**Issue by ioquatix** [actions/deploy-pages#344]
Not sure why this happens, but looks like the schema validation in VSCode reports this error:

![image](https://github.com/actions/deploy-pages/assets/30030/d1cb625a-ae29-4927-823f-567ea58b4d0c)

It's a little confusing as I believe this is actually correct.

**Comment by yoannchaudet** [comment]
Cannot see the whole workflow in the screenshot but GitHub Pages does not really own the VS code extension anyway.

Would you mind asking in https://github.com/orgs/community/discussions/categories/actions?discussions_q=is%3Aunanswered+category%3AActions?

**Comment by ioquatix** [comment]
It would be this one https://github.com/socketry/async/blob/main/.github/workflows/documentation.yaml which I use across multiple projects.

I suppose there must be a schema for this file, defined by VSCode, which doesn't take into account GitHub pages...

**Comment by ioquatix** [comment]
I found the schema and created an issue ☝🏼

**Comment by NicoWeio** [comment]
Just to stress: This means that the *example code from this action's README* yields a linting error.
I just filed a crude PR upstream (https://github.com/actions/languageservices/pull/80).

**Comment by NicoWeio** [comment]
Whoa, looks like our efforts were totally misdirected.

Apparently, the GitHub Actions extension performs a lookup for existing environments in one's repo and complains about any non-existing ones, even though the workflow might run fine and just create one.
See https://github.com/github/vscode-github-actions/issues/215

**Comment by yoannchaudet** [comment]
Closing this issue because it is not actionable from that Action.
