### ISSUE TITLE
[Bug] : Vite React Application Asset Build Not Coming 

### ISSUE THREAD

**Issue by XCoder-Ayush** [actions/deploy-pages#365]
This is the workflow run.

https://github.com/XCoder-Ayush/bloginary-client/actions/runs/10222259682

Inside the docker container, some sort of copy command error is there due to which assets folder which is essentially an artifact after the build process is not being copied when the GA triggers CI and CD to deploy in Github Pages.

![image](https://github.com/user-attachments/assets/1235aaf2-ec08-4ca6-ba63-dda4173c9cd9)

{No assets artifact found after successful build referred in the workflow run link above)

**Comment by yoannchaudet** [comment]
The community forum is the right place for help regarding 404 errors.

Also see https://github.com/orgs/community/discussions/61073.
