### ISSUE TITLE
Branch gh-pages not created 

### ISSUE THREAD

**Issue by saguileran** [actions/deploy-pages#382]
Hello!

I'm using this GitHub action and it works perfectly. Although I don't understand how it is deploying the web because the action doesn't create any branch. Can I configure the action to create a new branch (gh-pages)? I need it to host files and be able to access them.

Thank you.

**Comment by GabenGar** [comment]
Access the for what purpose? The whole point of actions is so you wouldn't need to pollute your repo with output file commits.

**Comment by saguileran** [comment]
I have some java files in the same folder I am deploying, but I cannot access to them because there is no link available.

**Comment by GabenGar** [comment]
Access from where?

**Comment by saguileran** [comment]
I just noticed I had the files mentioned in the gitignored file. Thanks for your help.

**Comment by GabenGar** [comment]
This only brings more questions. if they are gitignored why do you want them in the build output?

**Comment by saguileran** [comment]
I gitignored them by error.
