### ISSUE TITLE
Error 404 for Single Page Applications (SPA)

### ISSUE THREAD

**Issue by paulocoutinhox** [actions/deploy-pages#43]
Hi,

Im making a project that is a SPA, and i want host on github instead of Netlify.

But github still not support redirect all to index.html.

How i can do it with this new deploy method?

Repository:
https://github.com/sqlitedb/sqlitedb.github.io

Workflow:
https://github.com/sqlitedb/sqlitedb.github.io/blob/main/.github/workflows/pages.yml

Error:
https://sqlitedb.github.io/about

Thanks.

**Comment by yoannchaudet** [comment]
https://github.com/actions/upload-pages-artifact/issues/3#issuecomment-1199926563
