### ISSUE TITLE
BUG: Action selects the first alphabetical artifact, not github-pages

### ISSUE THREAD

**Issue by henryiii** [actions/deploy-pages#44]
The current action does not select an artifact named `github-pages`, like [the documentation says](https://github.com/actions/deploy-pages/blob/38e42fe573914db9c25acd6985009394bc350db4/README.md?plain=1#L15), but instead the first alphabetical artifact:

https://github.com/actions/deploy-pages/blob/38e42fe573914db9c25acd6985009394bc350db4/src/deployment.js#L49

Example:

https://github.com/henryiii/hello-world-pages/runs/7589251565?check_suite_focus=true

This is the changeset from passing to failing:

https://github.com/henryiii/hello-world-pages/commit/d487a4cc5f3f370b23b1457aac2c16e3f0e79f90

Real world failure fixed by adding a `z-` prefix to all artifacts: https://github.com/kratsg/faculty-statements/commit/f092ceeb261eb7a6ad4d3f322668d9148a64f426 🤣 

Debugging this with @kratsg, who kindly lent me his page to try out the new actions on.

**Comment by yoannchaudet** [comment]
Thank you for opening that! We will add filtering on the first page or artifacts.

**Comment by YiMysty** [comment]
👋 This issue has been fixed thru https://github.com/actions/deploy-pages/pull/46. The actions now looks into name with default value `github-pages` or provided name.

Close it for now, let us know if you have further questions :)
