### ISSUE TITLE
Question: Deployment error instead of skipped when triggered from pull-request

### ISSUE THREAD

**Issue by feryardiant** [actions/deploy-pages#45]
Hi there,

Just try out this action to deploy our website, I noticed that if the workflow is triggered by pull-request it's error without any info, like this

<img width="844" alt="Screen Shot 2022-08-01 at 05 24 08" src="https://user-images.githubusercontent.com/508665/182047675-f14f2d83-c601-4661-a057-3cb9b77ad566.png">

while in [the documentation](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site) stated as it should be skipped

> This step is skipped if the workflow was triggered by a pull request.

Is it a bug or actually an expected feature?

Regards,

**Comment by feryardiant** [comment]
Apparently it still needs to have [`if: github.event_name == 'push'`](https://github.com/creasico/creasico.github.io/blob/d5f039805db8e1cb30e40321af13330ee54f3c56/.github/workflows/main.yml#L54-L57) to make it skipped on pull-request.

```yml
deploy:
  runs-on: ubuntu-latest
  if: github.event_name == 'push'
  needs: build
```

<img width="908" alt="Screen Shot 2022-08-01 at 05 43 23" src="https://user-images.githubusercontent.com/508665/182048270-cdc9bc66-e429-44ec-b2b6-959f6a00e4a9.png">

**Comment by yoannchaudet** [comment]
@feryardiant Thank you for opening this. We will correct the documentation. We have decided to have the starter workflows only trigger on the default branch and not track pull requests at the moment (e.g. [here](https://github.com/actions/starter-workflows/blob/4a8f18e34dd13d2b6ee4d8da2ba72629eafe1609/pages/hugo.yml#L5-L7)).

**Comment by NicolasMassart** [comment]
Having it running from pull-request would be awesome as it would enable to host previews of the sites in pages.
(ideally in a subfolder like `https://user.github.io/project/pull-request/123/`)

**Comment by yoannchaudet** [comment]
Well I am late but the documentation change was merged a while ago!

@NicolasMassart One day!

**Comment by proppy** [comment]
@yoannchaudet salut! I think the documention is still erroneously mentioning that `deploy` steps are skipped on pull request:
https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site

> If the workflow was triggered by a push to the default branch, use the [actions/deploy-pages](https://github.com/actions/deploy-pages) action to deploy the artifact. This step is skipped if the workflow was triggered by a pull request.
