### ISSUE TITLE
Content deployment failure

### ISSUE THREAD

**Issue by oliverbenns** [actions/deploy-pages#68]
When building an app with `create-react-app` and then running this deploy action, I get the following error:

```
Artifact could not be deployed. Please ensure the content does not contain any hard links, symlinks and total size is less than 10GB.
```

However none of my build content seems to violate these conditions. I'm actually not sure what a hard link is in this context. Please see the run here: https://github.com/oliverbenns/joy-theme-creator/actions/runs/3147053516/jobs/5116187912

**Comment by yoannchaudet** [comment]
I really suggest you use https://github.com/actions/upload-pages-artifact for uploading your artifacts in a format GitHub Pages understands.

Here is an [example](https://github.com/actions/starter-workflows/blob/7bc6d15b952547f496b440a3ae79ec141de3df5a/pages/static.yml#L35-L39).

**Comment by oliverbenns** [comment]
Ah, many thanks.

For anyone stumbling here, I was using `actions/upload-artifact` when I should have been using `actions/upload-pages-artifact`.
