### ISSUE TITLE
Error: Ensure GITHUB_TOKEN has permission "idToken: write".

### ISSUE THREAD

**Issue by mathiasbynens** [actions/deploy-pages#71]
A workflow that was working fine for weeks suddenly [stopped working](https://github.com/mathiasbynens/tibia-bosses/actions/runs/3294515721/jobs/5432115686#step:2:1) with the following error message:

```
Run actions/deploy-pages@v1
Error: Error message: Cannot read properties of undefined (reading 'message')
    at Function.<anonymous> (/home/runner/work/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/@actions/core/lib/oidc-utils.js:71:1)
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/@actions/core/lib/oidc-utils.js:6:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Ensure GITHUB_TOKEN has permission "idToken: write".
```

Any ideas as to what might have happened?

The relevant workflow is here: https://github.com/mathiasbynens/tibia-bosses/blob/5a2f78b8a9a325ca0f5f1d709421b2239532826e/.github/workflows/build.yml#L30-L38

**Comment by yoannchaudet** [comment]
Thank you for opening this. It looks to have been a transient issue around OIDC. We are looking at it now.

Your following deployment succeeded and I have no reasons to believe you will run into this issue again in a non-random fashion.

**Comment by mathiasbynens** [comment]
Thanks! I can confirm a subsequent run a few hours later, without any code changes on my end, worked fine.

**Comment by Manoj-nathwani** [comment]
This did the trick for me - https://stackoverflow.com/a/76883315/2068836
