### ISSUE TITLE
Gets stuck in large deployment with no "Current status:" output 

### ISSUE THREAD

**Issue by alansill** [actions/deploy-pages#72]
The deploy-pages action appears to get stuck after the "Current status: finished_file_sync" step with no information after the "Current status: " line on built-in status checks for large static file repository deployments. The transferred artifact from the upload-pages-artifact step was 5.3 GB with an indicated raw size of 8.0 GB, both well below the 10 GB limit, and the GitHub-pages artifact is successfully uploaded. The deploy-pages action receives this corrrectly and proceeds through the "deployment_in_progress", "syncing_files", and "finished_file_sync" steps as listed by the "Current status:" line, but then the action continues with no output beyond the "Current status:" message until the timeout is reached. This happens even if the timeout is increased to large values.

To gain insight as to what is happening, further detail is needed in the "Current status:" output and more clarity on the expected steps is needed. Additionally, it would be helpful to produce a multi-step method of splitting up deployment of large static sites using actions so that the site deployment can be handled in stages rather than all at once. Note no processing of any sort is taking place as the site has already been prepared as a complete set of static files, only the deployment to GitHub Pages needs to be processed.

**Comment by yoannchaudet** [comment]
Hello!

If you can provide us for which repo you are seeing this behavior we may be able to investigate.

Just to clarify, 10GB is the hard artifacts limits for Pages. The [official limit for Pages sites is 1GB ](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits)so you are 8 times over.

It is obviously very expensive to move 8GB worth of static assets into GitHub Pages. Your content is getting replicated and made available across the whole planet. The best I can recommend is to try to understand why your site is so heavy and how it can be slimmed down (and potentially broken down into multiple smaller sites). 

We have no immediate plans to allow incremental deployments of Pages sites but it is something we are not discarding in the future.

**Comment by alansill** [comment]
This is a crucial archive of an important historical site on which grid computing was founded and nurtured through the early 2000s thruogh today. We have switched all new development to our GitHub organization, but would like to field this archive for reference for previous work. This is non-trivially important for reference for future work and to establish provenance for this work. Once the siteis built, it is unlikely to be buitl again, so getting through it once is important.

**Comment by alansill** [comment]
It seems happy at 3.8 GB total size passed between the "Upload artifact" and "Deploy to GitHub Pages" steps. My issue is not with the total sizes, which we can probably handle by paying for a deployment perhaps, but pointing out the non-communication of status and the lack of clarity on the sequence of steps. As a feature request I think it would be helpful for all concerned if these were spelled out in more detail, and if insight were provided into the expected sequence of messages from the "Current status:" output. 

Basically, I think the status output could be more informative. And yes, 8 GB is not a lot of content for a site of this nature. If you're concerned about the load, then it would be better to put limits on frequency of deployment or better yet, as mentioned above allow for incremental updates. I actually don't understand why it's any load at all to deploy previously formatted and processed static content, or what is going on in the deployment that takes so long. Just asking for insight so that we can optimize each step. Thanks.

**Comment by alansill** [comment]
Closed as I found an alternative way to store the data. The workflow could still use better labeling of steps and progress, however.
