### ISSUE TITLE
My github page can not deploy due to code

### ISSUE THREAD

**Issue by zhaochenyang20** [actions/deploy-pages#81]
Sorry for interruption, but my page are confronted with deploy failure that I can solve:

```shell
Warning: Input 'emit_telemetry' has been deprecated with message: Use of this input causes the action to do nothing. You should remove this build step from your workflow.
Run actions/deploy-pages@v1
Actor: github-pages[bot]
Action ID: 3541027231
Artifact URL: https://pipelines.actions.githubusercontent.com/vkHFzCL7Y5132px1YFZ6UPIsAtJbQxnm92SclbH7tXlkxLxmBM/_apis/pipelines/workflows/3541027231/artifacts?api-version=6.0-preview
{"count":1,"value":[{"containerId":14471415,"size":994406400,"signedContent":null,"fileContainerResourceUrl":"https://pipelines.actions.githubusercontent.com/vkHFzCL7Y5132px1YFZ6UPIsAtJbQxnm92SclbH7tXlkxLxmBM/_apis/resources/Containers/14471415","type":"actions_storage","name":"github-pages","url":"https://pipelines.actions.githubusercontent.com/vkHFzCL7Y5132px1YFZ6UPIsAtJbQxnm92SclbH7tXlkxLxmBM/_apis/pipelines/1/runs/1028/artifacts?artifactName=github-pages","expiresOn":"2022-[11](https://github.com/zhaochenyang20/zhaochenyang20.github.io/actions/runs/3541027231/jobs/5944888374#step:2:12)-25T[13](https://github.com/zhaochenyang20/zhaochenyang20.github.io/actions/runs/3541027231/jobs/5944888374#step:2:14):32:20.9022685Z","items":null}]}
Creating deployment with payload:
{
	"artifact_url": "https://pipelines.actions.githubusercontent.com/vkHFzCL7Y5132px1YFZ6UPIsAtJbQxnm92SclbH7tXlkxLxmBM/_apis/pipelines/1/runs/1028/artifacts?artifactName=github-pages&%24expand=SignedContent",
	"pages_build_version": "bda42ea19565838adf21ac3de6acdf037abcb23b",
	"oidc_token": "***"
}
Created deployment for bda42ea[19](https://github.com/zhaochenyang20/zhaochenyang20.github.io/actions/runs/3541027231/jobs/5944888374#step:2:20)565838adf21ac3de6acdf037abcb23b
{"page_url":"https://zhaochenyang[20](https://github.com/zhaochenyang20/zhaochenyang20.github.io/actions/runs/3541027231/jobs/5944888374#step:2:21).github.io/","status_url":"https://api.github.com/repos/zhaochenyang20/zhaochenyang20.github.io/pages/deployment/status/bda42ea19565838adf21ac3de6acdf037abcb23b","preview_url":""}
Unable to get deployment status.
Unable to get deployment status.
Unable to get deployment status.
Unable to get deployment status.
Unable to get deployment status.
Unable to get deployment status.
Unable to get deployment status.
Unable to get deployment status.
Unable to get deployment status.
Unable to get deployment status.
Too many errors, aborting!
Error: Failed with status code: 200
Deployment cancelled with https://api.github.com/repos/zhaochenyang20/zhaochenyang20.github.io/pages/deployment/cancel/bda42ea19565838adf[21](https://github.com/zhaochenyang20/zhaochenyang20.github.io/actions/runs/3541027231/jobs/5944888374#step:2:22)ac3de6acdf037abcb[23](https://github.com/zhaochenyang20/zhaochenyang20.github.io/actions/runs/3541027231/jobs/5944888374#step:2:24)b
```

**Comment by zhaochenyang20** [comment]
Actually, my page has had some problems with deployment several times before, but I can fix it simply by re-running failed actions.

This time, I re-run tens of times, and I even re-commit my hexo to make a new build, but with no help, It still can not be deployed.

**Comment by zhaochenyang20** [comment]
You can see this:

https://github.com/zhaochenyang20/zhaochenyang20.github.io/actions/runs/3541027231/jobs/5944888374

**Comment by zhaochenyang20** [comment]
What does this means？

> Unable to get deployment status.

**Comment by zhaochenyang20** [comment]
I am crying about this because my home work is deployed on my GitHub page. 

ovo

# plz help!

**Comment by stla** [comment]
Same problem for me: https://github.com/laustep/stlahblog/actions/runs/3541306609

**Comment by VesaJuvonen** [comment]
Same problem in our automation, so adding this annoying +1 message to push the importance of getting this issue fixed. Timing is not great given the Thanksgiving today, but hopefully things are sorted out soon.

**Comment by sm1990** [comment]
We've been unable to do a deployment for 7hrs now.

**Comment by SQLDBAWithABeard** [comment]
Yup - Also have the same issue

**Comment by Parking-Master** [comment]
I've been making a HUGE game on github pages, and can't update content on the website: www.fps2.ml

I have the same exact problem: https://github.com/Parking-Master/FPS2/actions/runs/3542118405/jobs/5947335575

I've re-ran all jobs several times, deleted 256 MB of files I don't need, deleted the workflow, and commited several times. Still the same problem

**Comment by Parking-Master** [comment]
How is there an error with a `200` response? Isn't that supposed to be a success?

**Comment by Parking-Master** [comment]
@VesaJuvonen Yeah that's what I was thinking, I always get some stupid problem that takes all day to fix, always on the special days.

**Comment by heitorlessa** [comment]
Same, nearly 8 hours later.

**Comment by Parking-Master** [comment]
@heitorlessa 16 hours

**Comment by ndw** [comment]
I've also been seeing this problem. It's been failing all day.

**Comment by Parking-Master** [comment]
So who's going to fix this? Is GitHub going to? I've gotta be able to update my repository. I'm feeling better knowing this isn't a _me_ problem, and that someone will fix it soon.

**Comment by ndw** [comment]
It's US Thanksgiving in the United States today. I expect they're running with reduced staff. Hopefully it's fixed sometime tomorrow.

**Comment by CODEXEDYX** [comment]
![Captura de pantalla 2022-11-24 181627](https://user-images.githubusercontent.com/106486226/203838639-790ec1ee-afdb-43b5-a456-0476743a9b27.png)

It tells me it's okay but when I see my website the js code doesn't work for me

**Comment by Parking-Master** [comment]
@ndw Yeah they can take their time/break and fix it whenever but I hope it's soon

**Comment by yoannchaudet** [comment]
See https://github.com/orgs/community/discussions/39907#discussioncomment-4229075

**Comment by zhaochenyang20** [comment]
I have fixed this now.
You can refer to this:

> I slept early last night because Github Action failed the previous night. Specifically, the CI/CD passed the build after my last commit, but the deployment always failed. For this, I asked Xun Sun and pie, and their advice was to re-run the failure and wait.
>
> But I have re-run it so many times, and it still failed.
>
> ```shell
> Warning: Input 'emit_telemetry' has been deprecated with message: Use of this input causes the action to do nothing. You should remove this build step from your workflow.
> Run actions/deploy-pages@v1
> Actor: github-pages[bot]
> Action ID: 3540368670
> Artifact URL: https://pipelines.actions.githubusercontent.com/vkHFzCL7Y5132px1YFZ6UPIsAtJbQxnm92SclbH7tXlkxLxmBM/_apis/pipelines/workflows/3540368670/artifacts?api-version=6.0-preview
> {"count":1,"value":[{"containerId":14469600,"size":994385920,"signedContent":null,"fileContainerResourceUrl":"https://pipelines.actions.githubusercontent.com/vkHFzCL7Y5132px1YFZ6UPIsAtJbQxnm92SclbH7tXlkxLxmBM/_apis/resources/Containers/14469600","type":"actions_storage","name":"github-pages","url":"https://pipelines.actions.githubusercontent.com/vkHFzCL7Y5132px1YFZ6UPIsAtJbQxnm92SclbH7tXlkxLxmBM/_apis/pipelines/1/runs/1010/artifacts?artifactName=github-pages","expiresOn":"2022-11-25T12:13:30.1538887Z","items":null}]}
> Creating deployment with payload:
> {
> 	"artifact_url": "https://pipelines.actions.githubusercontent.com/vkHFzCL7Y5132px1YFZ6UPIsAtJbQxnm92SclbH7tXlkxLxmBM/_apis/pipelines/1/runs/1010/artifacts?artifactName=github-pages&%24expand=SignedContent",
> 	"pages_build_version": "6dc0a7511f28e9522819959158980cd8518904f7",
> 	"oidc_token": "***"
> }
> Created deployment for 6dc0a7511f28e9522819959158980cd8518904f7
> {"page_url":"https://zhaochenyang20.github.io/","status_url":"https://api.github.com/repos/zhaochenyang20/zhaochenyang20.github.io/pages/deployment/status/6dc0a7511f28e9522819959158980cd8518904f7","preview_url":""}
> Unable to get deployment status.
> Unable to get deployment status.
> Unable to get deployment status.
> Unable to get deployment status.
> Unable to get deployment status.
> Unable to get deployment status.
> Unable to get deployment status.
> Unable to get deployment status.
> Unable to get deployment status.
> Unable to get deployment status.
> Too many errors, aborting!
> Error: Failed with status code: 200
> Deployment cancelled with https://api.github.com/repos/zhaochenyang20/zhaochenyang20.github.io/pages/deployment/cancel/6dc0a7511f28e9522819959158980cd8518904f7
> ```
>
> Xun Sun asked me to read the documentation and raise an issue.
>
> So I did these:
>
> https://github.com/actions/deploy-pages
>
> https://github.com/actions/deploy-pages/issues/81
>
> So, I broke my defence last night. I even re-committed twice, and it still failed.
>
> However, I re-ran the Action four days ago and was surprised when it passed this time. Holder told me my error was not even found on Google, proving this is a niche issue. In addition, deployment is theoretically the easiest, copy the build to the server and open an HTTPS interface.
>
> I also thought it was a GitHub problem, so I went downstairs to bed at 10:00.
>
> To my surprise, Catherine told me in the morning that she saw what I wrote yesterday. However, didn't I fail the CI / CD?
>
> To be precise, the actions of Nov 23 didn't work, and I re-run all the actions of Nov 11. I realised that GitHub action seems to be much simpler than I thought.
>
> In short, the action under any commit repeats the following steps:
>
> 1. simply pull the latest commit of the main branch.
>
> 2. build and deploy.
>
> As a result, the CI/CD from a few days ago passed over my commit of yesterday.
>
> This morning, I found out that all the work can be done right now. Then I checked the issue, maybe the server crashed on Thanksgiving.
>
> Anyway, the solution is to re-run and wait...

**Comment by zhaochenyang20** [comment]
Anyway, the solution is to re-run and wait...

**Comment by zhaochenyang20** [comment]
![image](https://user-images.githubusercontent.com/74843776/203882081-083836f6-e6e9-4733-832a-22b6bab094db.png)
