### ISSUE TITLE
Assets in Git LFS are not added to artifact

### ISSUE THREAD

**Issue by exodrifter** [actions/deploy-pages#88]
If you use Git LFS with this action, the LFS pointer to the asset is added to the artifact instead of the actual asset.

For example, in the artifact produced by this [run](https://github.com/exodrifter/exodrifter-vods/actions/runs/3791858993), the `assets/images/avatar.jpg` file contains the following plaintext instead of the image:
```
version https://git-lfs.github.com/spec/v1
oid sha256:967609522a3a0f4c5acf31218836c053d27309f6cfe1f05d6a1a821fbe882143
size 18151
```

Indeed, when I try to curl the file in the deployment, I get the very same LFS pointer.
```
$ curl https://vods.exodrifter.space/assets/images/avatar.jpg
version https://git-lfs.github.com/spec/v1
oid sha256:967609522a3a0f4c5acf31218836c053d27309f6cfe1f05d6a1a821fbe882143
size 18151
```

The action should use the actual asset when producing the artifact, not the LFS pointer.

**Comment by yoannchaudet** [comment]
By default `actions/checkout` does not retrieve LFS assets (see [doc](https://github.com/actions/checkout#usage)).

You can fix that in your workflow there: https://github.com/exodrifter/exodrifter-vods/actions/runs/3791858993/workflow#L27-L28.

```
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
```
