### ISSUE TITLE
Timeout when pushed by some users

### ISSUE THREAD

**Issue by sim642** [actions/deploy-pages#92]
I have an issue, where some users who push to my repository with this action set up, the deployment eventually fails. The log for it looks like this:
```
Current status: deployment_queued
[...]
Current status: deployment_queued
Current status: deployment_in_progress
[...]
Current status: deployment_in_progress
Timeout reached, aborting!
```
The timeout happens after 10 minutes.
However, it works just fine for some other users.

There's also a link to a JSON result containing the message

> API rate limit exceeded for XX.YY.ZZ.WW. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

Not sure what to make of it though.

**Comment by yoannchaudet** [comment]
How large is the artifact you are intending to deploy? We had a lo g outage yesterday which caused all deployments to timeout for a part of the day. Large artifacts can also cause troubles especially if above the [service limits](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#limits-on-use-of-github-pages).

**Comment by yoannchaudet** [comment]
Let us know. Closing in mean time.
